import { spawn, spawnSync } from "node:child_process";
import { access, mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { constants as fsConstants } from "node:fs";
import { homedir } from "node:os";
import path from "node:path";

import { ensureProject, runAgentCommand } from "../../secureskills-core/src/index.ts";
import { pathExists, removeIfExists, writeJsonFile } from "../../secureskills-core/src/fs-utils.ts";

const PROFILE_BLOCK_START = "# >>> Plato Codex integration >>>";
const PROFILE_BLOCK_END = "# <<< Plato Codex integration <<<";

interface CodexIntegrationMarker {
  version: number;
  enabledAt: string;
}

export interface CodexIntegrationOptions {
  platoHomeDir?: string;
  shellProfilePath?: string;
  realCodexPath?: string;
}

export interface CodexEnableResult {
  repoRoot: string;
  initializedProject: boolean;
  shellHookPath: string;
  shellProfilePath: string;
  realCodexPath: string;
  shellHookUpdated: boolean;
}

export interface CodexDisableResult {
  repoRoot: string;
  disabled: boolean;
}

export interface CodexDoctorReport {
  repoRoot: string | null;
  repoEnabled: boolean;
  shellHookPath: string;
  shellHookInstalled: boolean;
  shellProfilePath: string;
  shellProfileConfigured: boolean;
  realCodexPathFile: string;
  realCodexPath: string | null;
  realCodexPathUsable: boolean;
  issues: string[];
}

export interface CodexShellInstallResult {
  shellHookPath: string;
  shellProfilePath: string;
  realCodexPath: string;
  shellHookUpdated: boolean;
}

interface CodexIntegrationPaths {
  platoHomeDir: string;
  shellDir: string;
  metadataDir: string;
  shellHookPath: string;
  realCodexPathFile: string;
  shellProfilePathFile: string;
}

export function defaultPlatoHomeDir(): string {
  return process.env.PLATO_HOME ?? path.join(homedir(), ".config", "plato");
}

export function defaultShellProfilePath(): string {
  return process.env.PLATO_SHELL_PROFILE ?? path.join(homedir(), ".zshrc");
}

function resolveIntegrationPaths(options: CodexIntegrationOptions = {}): CodexIntegrationPaths {
  const platoHomeDir = options.platoHomeDir ?? defaultPlatoHomeDir();
  return {
    platoHomeDir,
    shellDir: path.join(platoHomeDir, "shell"),
    metadataDir: path.join(platoHomeDir, "metadata"),
    shellHookPath: path.join(platoHomeDir, "shell", "codex.zsh"),
    realCodexPathFile: path.join(platoHomeDir, "metadata", "codex-path"),
    shellProfilePathFile: path.join(platoHomeDir, "metadata", "shell-profile"),
  };
}

function codexMarkerPath(repoRoot: string): string {
  return path.join(repoRoot, ".secureskills", "integrations", "codex.json");
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

async function ensureIntegrationDirectories(paths: CodexIntegrationPaths): Promise<void> {
  await mkdir(paths.shellDir, { recursive: true });
  await mkdir(paths.metadataDir, { recursive: true });
}

async function readStoredShellProfilePath(paths: CodexIntegrationPaths): Promise<string | null> {
  if (!(await pathExists(paths.shellProfilePathFile))) {
    return null;
  }

  return (await readFile(paths.shellProfilePathFile, "utf8")).trim() || null;
}

async function readStoredRealCodexPath(paths: CodexIntegrationPaths): Promise<string | null> {
  if (!(await pathExists(paths.realCodexPathFile))) {
    return null;
  }

  return (await readFile(paths.realCodexPathFile, "utf8")).trim() || null;
}

async function fileIsExecutable(targetPath: string | null): Promise<boolean> {
  if (!targetPath) {
    return false;
  }

  try {
    const stats = await stat(targetPath);
    if (!stats.isFile()) {
      return false;
    }
    await access(targetPath, fsConstants.X_OK);
    return true;
  } catch {
    return false;
  }
}

async function resolveRealCodexPath(
  paths: CodexIntegrationPaths,
  options: CodexIntegrationOptions = {},
): Promise<string> {
  const candidatePaths = [
    options.realCodexPath,
    process.env.PLATO_CODEX_REAL_PATH,
    await readStoredRealCodexPath(paths),
  ];

  for (const candidate of candidatePaths) {
    if (await fileIsExecutable(candidate ?? null)) {
      return candidate!;
    }
  }

  const lookup = spawnSync(process.env.SHELL ?? "/bin/sh", ["-lc", "command -v codex"], {
    encoding: "utf8",
    env: process.env,
  });

  if (lookup.error) {
    throw lookup.error;
  }

  const resolved = lookup.stdout.trim();
  if (lookup.status === 0 && resolved) {
    return resolved;
  }

  throw new Error('Could not find the real "codex" binary on PATH. Install Codex first, then run "secureskills enable codex".');
}

function shellHookContents(paths: CodexIntegrationPaths): string {
  return `# Generated by Plato. Safe to recreate.\n_plato_codex_real_path_file=${shellQuote(paths.realCodexPathFile)}\n\n_plato_codex_real_bin() {\n  if [[ ! -f "$_plato_codex_real_path_file" ]]; then\n    return 1\n  fi\n\n  local plato_real_codex\n  IFS= read -r plato_real_codex < "$_plato_codex_real_path_file" || return 1\n  if [[ -z "$plato_real_codex" || ! -x "$plato_real_codex" ]]; then\n    return 1\n  fi\n\n  printf '%s\\n' "$plato_real_codex"\n}\n\ncodex() {\n  local plato_real_codex\n  if ! plato_real_codex=\"$(_plato_codex_real_bin)\"; then\n    echo \"Plato: real codex path is missing. Run 'secureskills doctor codex'.\" >&2\n    return 127\n  fi\n\n  if [[ -n \"\${PLATO_CODEX_BYPASS:-}\" ]]; then\n    command \"$plato_real_codex\" \"$@\"\n    return $?\n  fi\n\n  if command -v secureskills >/dev/null 2>&1; then\n    secureskills launch codex -- \"$@\"\n    return $?\n  fi\n\n  command \"$plato_real_codex\" \"$@\"\n}\n`;
}

function profileSourceBlock(shellHookPath: string): string {
  return `${PROFILE_BLOCK_START}\n[ -f ${shellQuote(shellHookPath)} ] && source ${shellQuote(shellHookPath)}\n${PROFILE_BLOCK_END}`;
}

async function upsertProfileSourceBlock(profilePath: string, shellHookPath: string): Promise<void> {
  const nextBlock = profileSourceBlock(shellHookPath);
  const existing = (await pathExists(profilePath)) ? await readFile(profilePath, "utf8") : "";
  const stripped = stripProfileSourceBlock(existing).trimEnd();
  const nextContents = stripped.length > 0 ? `${stripped}\n\n${nextBlock}\n` : `${nextBlock}\n`;
  await mkdir(path.dirname(profilePath), { recursive: true });
  await writeFile(profilePath, nextContents, "utf8");
}

function stripProfileSourceBlock(contents: string): string {
  const blockPattern = new RegExp(`${PROFILE_BLOCK_START}[\\s\\S]*?${PROFILE_BLOCK_END}\\n?`, "g");
  return contents.replace(blockPattern, "");
}

async function removeProfileSourceBlock(profilePath: string): Promise<void> {
  if (!(await pathExists(profilePath))) {
    return;
  }

  const existing = await readFile(profilePath, "utf8");
  const stripped = stripProfileSourceBlock(existing).trimEnd();
  await writeFile(profilePath, stripped.length > 0 ? `${stripped}\n` : "", "utf8");
}

async function installShellHook(paths: CodexIntegrationPaths, shellProfilePath: string, realCodexPath: string): Promise<void> {
  await ensureIntegrationDirectories(paths);
  await writeFile(paths.shellHookPath, shellHookContents(paths), "utf8");
  await writeFile(paths.realCodexPathFile, `${realCodexPath}\n`, "utf8");
  await writeFile(paths.shellProfilePathFile, `${shellProfilePath}\n`, "utf8");
  await upsertProfileSourceBlock(shellProfilePath, paths.shellHookPath);
}

export async function installCodexShellHook(
  options: CodexIntegrationOptions = {},
): Promise<CodexShellInstallResult> {
  const paths = resolveIntegrationPaths(options);
  const shellProfilePath = options.shellProfilePath ?? await readStoredShellProfilePath(paths) ?? defaultShellProfilePath();
  const realCodexPath = await resolveRealCodexPath(paths, options);
  const storedRealCodexPath = await readStoredRealCodexPath(paths);
  const shellHookInstalled = await pathExists(paths.shellHookPath);
  const shellProfileConfigured = await profileHasSourceBlock(shellProfilePath);
  const shellHookUpdated = !shellHookInstalled || !shellProfileConfigured || storedRealCodexPath !== realCodexPath;

  await installShellHook(paths, shellProfilePath, realCodexPath);

  return {
    shellHookPath: paths.shellHookPath,
    shellProfilePath,
    realCodexPath,
    shellHookUpdated,
  };
}

async function currentRepoMarker(startDir: string): Promise<string | null> {
  let currentDir = path.resolve(startDir);

  while (true) {
    const markerPath = codexMarkerPath(currentDir);
    if (await pathExists(markerPath)) {
      return currentDir;
    }

    const parentDir = path.dirname(currentDir);
    if (parentDir === currentDir) {
      return null;
    }
    currentDir = parentDir;
  }
}

export async function discoverProjectRoot(startDir: string): Promise<string | null> {
  let currentDir = path.resolve(startDir);

  while (true) {
    if (await pathExists(path.join(currentDir, ".secureskills"))) {
      return currentDir;
    }

    const parentDir = path.dirname(currentDir);
    if (parentDir === currentDir) {
      return null;
    }
    currentDir = parentDir;
  }
}

async function spawnPassthrough(command: string[], cwd: string): Promise<number> {
  return await new Promise<number>((resolve, reject) => {
    const child = spawn(command[0], command.slice(1), {
      cwd,
      stdio: "inherit",
      env: {
        ...process.env,
        PLATO_CODEX_BYPASS: "1",
      },
    });

    child.on("error", reject);
    child.on("exit", (code) => resolve(code ?? 1));
  });
}

export async function enableCodexForRepo(
  repoRoot: string,
  options: CodexIntegrationOptions = {},
): Promise<CodexEnableResult> {
  const { project, initializedProject } = await ensureProject(repoRoot);
  const shellInstall = await installCodexShellHook(options);
  await writeJsonFile(codexMarkerPath(project.rootDir), {
    version: 1,
    enabledAt: new Date().toISOString(),
  } satisfies CodexIntegrationMarker);

  return {
    repoRoot: project.rootDir,
    initializedProject,
    shellHookPath: shellInstall.shellHookPath,
    shellProfilePath: shellInstall.shellProfilePath,
    realCodexPath: shellInstall.realCodexPath,
    shellHookUpdated: shellInstall.shellHookUpdated,
  };
}

export async function disableCodexForRepo(repoRoot: string): Promise<CodexDisableResult> {
  const markerPath = codexMarkerPath(repoRoot);
  const disabled = await pathExists(markerPath);
  await removeIfExists(markerPath);
  return {
    repoRoot,
    disabled,
  };
}

export async function doctorCodex(
  startDir: string,
  options: CodexIntegrationOptions = {},
): Promise<CodexDoctorReport> {
  const paths = resolveIntegrationPaths(options);
  const shellProfilePath = options.shellProfilePath ?? await readStoredShellProfilePath(paths) ?? defaultShellProfilePath();
  const shellHookInstalled = await pathExists(paths.shellHookPath);
  const shellProfileConfigured = await profileHasSourceBlock(shellProfilePath);
  const realCodexPath = await readStoredRealCodexPath(paths);
  const realCodexPathUsable = await fileIsExecutable(realCodexPath);
  const repoRoot = await currentRepoMarker(startDir);
  const issues: string[] = [];

  if (!shellHookInstalled) {
    issues.push(`Missing shell hook: ${paths.shellHookPath}`);
  }
  if (!shellProfileConfigured) {
    issues.push(`Shell profile is missing the Plato source block: ${shellProfilePath}`);
  }
  if (!realCodexPathUsable) {
    issues.push(`Real codex path is missing or not executable: ${paths.realCodexPathFile}`);
  }

  return {
    repoRoot,
    repoEnabled: repoRoot !== null,
    shellHookPath: paths.shellHookPath,
    shellHookInstalled,
    shellProfilePath,
    shellProfileConfigured,
    realCodexPathFile: paths.realCodexPathFile,
    realCodexPath,
    realCodexPathUsable,
    issues,
  };
}

async function profileHasSourceBlock(profilePath: string): Promise<boolean> {
  if (!(await pathExists(profilePath))) {
    return false;
  }

  const contents = await readFile(profilePath, "utf8");
  return contents.includes(PROFILE_BLOCK_START) && contents.includes(PROFILE_BLOCK_END);
}

export async function launchCodex(
  commandArguments: string[],
  startDir: string,
  options: CodexIntegrationOptions = {},
): Promise<number> {
  const paths = resolveIntegrationPaths(options);
  const realCodexPath = await resolveRealCodexPath(paths, options);
  const repoRoot = await currentRepoMarker(startDir);

  if (!repoRoot) {
    return spawnPassthrough([realCodexPath, ...commandArguments], startDir);
  }

  return runAgentCommand(repoRoot, [realCodexPath, ...commandArguments], {
    launchFromDir: startDir,
    env: {
      ...process.env,
      PLATO_CODEX_BYPASS: "1",
    },
  });
}

export async function cleanupCodexShellIntegration(options: CodexIntegrationOptions = {}): Promise<void> {
  const paths = resolveIntegrationPaths(options);
  const shellProfilePath = options.shellProfilePath ?? await readStoredShellProfilePath(paths) ?? defaultShellProfilePath();
  await removeProfileSourceBlock(shellProfilePath);
  await rm(paths.platoHomeDir, { recursive: true, force: true });
}
